version: 0.2

env:
  variables:
    APP_NAME: ""
    DOCKER_REPOSITORY_NAME: ""
    DOCKER_REGISTRY_URL: ""
    DOCKER_REGISTRY_REGION: "us-east-1"
    DOCKER_PREV_ENV_TAG: "dev"
    ADD_DOCKER_LATEST_TAG: "true"
    DOCKER_ENV_TAG: "production"

phases:
  install:
    runtime-versions:
      docker: 19

    commands:
      # Update system packages
      - apt-get update -y -q --list-cleanup || true
  build:
    commands:
      - echo Docker image tag update started on `date`
      - cd ./${APP_NAME} && bash ./scripts/update-image-tag.sh
      - echo Tag update completed on `date`

artifacts:
  files:
    - image-def.json
